### ISSUE TITLE
mistake in formulaWindow.py

### ISSUE THREAD

**Issue by retrue** [MrCHB1/UniFract-II#2]
I am not a programmer and I have spent the last two hours trying to make run the program using the most update version of the source. I didn't even know how to install or run pip and as always, there are always missing dependencies. That is, just installing what is in requirements.txt is not enough.
Anyway, I think there is an error in line 18 of formulaWindow.py
Where it says:
self.z = open("src/main.py", "r")
it should be:
self.z = open("main.py", "r")

If not, you get a FileNotFound error and the program doesn't start.

**Comment by MrCHB1** [comment]
> I am not a programmer and I have spent the last two hours trying to make run the program using the most update version of the source. I didn't even know how to install or run pip and as always, there are always missing dependencies. That is, just installing what is in requirements.txt is not enough.
> Anyway, I think there is an error in line 18 of formulaWindow.py
> Where it says:
> self.z = open("src/main.py", "r")
> it should be:
> self.z = open("main.py", "r")
> 
> If not, you get a FileNotFound error and the program doesn't start.

Fixed, not found in the releases page but you can download the source code directly.
